### ISSUE TITLE
Post TLA Statistics integration (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/Token-Launch-Auction#2]
### Showcase our TLA statistics to further excite the public on our product interest and its mission.

DATA SET
1. 1859/New token holders
2. 24,774,879/USDC raised
3. (1:05:20:47 or COMPLETED) /Time left
4. 51%/POP sold.

## Source File
- https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=3629%3A32268

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should be the same as the design.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2021-12-03 at 12.50.39 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8717f780-978f-4d4e-868a-0fc409eda003)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Token-Launch-Auction-603eb49d1a9a0b0011b49b36/issues/popcorndao/Token-Launch-Auction/2?planning-poker) with ZenHub @bhanusanghi @ecmendenhall @leomarlo @RedVeil @thenerdcat

**Comment by RedVeil** [comment]
Now that quite some time has passed since the TLA. Should we close the ticket? Or is still important to display this?
